In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.array(([1, 0, 0], [0, 1, 0], [0, 0, 1]))==np.eye(3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
lista = [2, 4, 6, 8, 10]
lista.pop(5)

IndexError: pop index out of range

In [14]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr.ndim

3

In [15]:
x = np.array([1, 2, 3, 4])

y = x[:-1]

x[0] = 9
y


array([9, 2, 3])

In [18]:
def func_x():

    xx = []

    for i in range(5):

        xx.append(i)

 

yy = []

def func_y():

    for i in range(5):

        yy.append(i)

func_x()

func_y()

print(yy)

[0, 1, 2, 3, 4]


In [19]:
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])

arr[1][1]

5

In [20]:

A = "data curation"

B = "data curation"

print(A is B)

False


In [21]:
A = True

B = True

print(A is B)

True


In [24]:
value = "Jane Doe"

def myFunction(parameter):

         value = "First"

         value = parameter

         print (value)

myFunction("Second")

Second
